language: node_js
node_js: stable
branches:
  only:
  - develop
before_install:
- npm install -g hexo
- npm install -g hexo-cli
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
  - cd ./public
  - git init
  - git config --global user.name 'Java-http'
  - git config --global user.email 'Java_http@163.com'
  - git add .
  - git commit -m "generate static resources, triggerd by travis ci"
  - git push --force --quiet "https://Java-http.github.io:${REPO_TOKEN}@${GH_REF}" master:master
env:
  global:
    - GH_REF: github.com/Java-http/Java-http.github.io.git
